name: ModernAC
main: com.modernac.ModernACPlugin
version: ${project.version}
api-version: 1.16
# PacketEvents обязателен в рантайме
depend: [packetevents]
softdepend: [ViaVersion]
commands:
  ac:
    description: AntiCheat main command
    aliases: [anticheat]
    permission: ac.use
    usage: /ac <info|debug|exempt|reload|devfake|status|inspect|lag>
permissions:
  ac.use:
    description: Allows use of /ac command
    default: op
  ac.alerts:
    description: Receive anticheat alerts
    default: op
  ac.command.info:
    description: Use /ac info
    default: op
  ac.command.debug:
    description: Use /ac debug
    default: op
  ac.command.exempt:
    description: Use /ac exempt
    default: op
  ac.command.reload:
    description: Use /ac reload
    default: op
  ac.command.lag:
    description: Use /ac lag
    default: op
  modernac.dev:
    description: Access developer commands
    default: op
