name: Build (Maven, JDK 17)

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build with Maven (tests enabled)
        run: |
          if [ -x ./mvnw ]; then
            ./mvnw -B -ntp clean package -DskipTests=false
          else
            mvn -B -ntp clean package -DskipTests=false
          fi

      - name: Upload plugin JAR
        uses: actions/upload-artifact@v4
        with:
          name: ModernAC-${{ github.sha }}
          path: |
            target/*.jar
            !target/*-sources.jar
            !target/*-javadoc.jar
          if-no-files-found: error
          retention-days: 10
          
